### PR TITLE
Chord refinement

### PR DESCRIPTION
**Pull request by chrisglein**
Add/refine chords for
- Drunken Sailor
- Leave Her Johnny
- Randy Dandy

### CODE REVIEW

**Comment by brewingcode** [comment]
I seem to like F-C in more places, we might need to pair program in person to figure out why. :P Also, something that is never marked on any of these, but that is implied for the accordion and I definitely failed to mention until now:

When a chord is marked, 99% of the time it's "play the marked root note and then the chord in time". So, taking something like the first measures of Drunken Sailor, the actual notes the accordion plays are:

image


```
K: Dm
M: 4/4
V:t clef=treble
V:b clef=bass
[V:t] "Am"a2 aa a2  aa | a2 d2 f2 a2 | "C"g2 gg g2 gg | g2 c2 e2 g2 |
w: What will we do with a drunk-en sail-or?
[V:b] A,,2 [A,,C,E,]2 A,,2 [A,,C,E,]2 A,,2 [A,,C,E,]2 A,,2 [A,,C,E,]2 
```

**Comment by brewingcode** [comment]
I still need to confirm Randy Dandy-O, will get to that later today.

**Comment by chrisglein** [comment]
Overall for the chords I aimed for "better than what was there before". I took notes last Tuesday on many and didn't like all of them upon hearing them fresh. I've been leveraging the abc midi playback site to test many of these. That's how I fixed the timing on some of the notes too - if you're off the bass chords get nasty. Also I'm the individual commits you can see links to sites I used to source some of the changes. 

But yes, many chords still need more work.

**Review by brewingcode — APPROVED** [review]
The lyrics and measures are lined up, and the chords are .... for accordion, anyway. I think we can re-jigger the chords in person.

**Comment by brewingcode** [comment]
Whoops, that was stupid of me, I made a bunch of changes in master on these three songs. I merged in master, and resolved all conflicts in favor of this branch. Sorry about that.

**Pull request merged**
